CREATE DATABASE NettrotDB;
GO

USE NettrotDB;
GO

CREATE TABLE Products (
ProductID INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(100) NOT NULL,
ProductCategory NVARCHAR(100) NOT NULL,
Price DECIMAL(10,2) NOT NULL,
Stock INT NOT NULL CHECK (Stock >= 0),
Description NVARCHAR(max),
ImageURL NVARCHAR(max)
);
GO

CREATE TABLE Users (
UserID INT IDENTITY(1,1) PRIMARY KEY,
Username NVARCHAR(50) NOT NULL,
PasswordHash NVARCHAR(255) NOT NULL,
Email NVARCHAR(100) NOT NULL UNIQUE,
CreatedAt DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE Purchases (
PurchaseID INT IDENTITY(1,1) PRIMARY KEY,
UserID INT FOREIGN KEY REFERENCES Users(UserID),
ProductID INT FOREIGN KEY REFERENCES Products(ProductID),
PurchaseDate DATETIME DEFAULT GETDATE(),
Quantity INT NOT NULL CHECK (Quantity > 0)
);
GO